# configs/fast_tri.yaml — varreduras rápidas em 3 tickers
data:
  tickers: ["BOVA11.SA", "BBDC4.SA", "BBAS3.SA"]
  start: "2018-01-01"
model:
  horizon: 5
  input_size: 60
  n_windows: 6
  step_size: 20
  max_steps: 10
  seed: 1
  lead_for_signal: 1
signals:
  exp_thresh: 0.0005
  consec: 1
  trend_sma: null
  dyn_thresh_k: 1.0
  vol_window: 20
  rsi_window: null
  rsi_min: null
  bb_window: null
  bb_k: 2.0
  atr_window: null
  atr_stop_k: null
  cooldown_bars: 0
  max_hold_bars: null
backtest:
  init_cash: 100000
  fees: 0.0005
  slippage: 0.0005
  direction: "longonly"
  only_non_overlapping: true
  risk_per_trade: null
tracking:
  use_mlflow: false
  mlflow_experiment: "fast"
  mlflow_uri: null
registry:
  enabled: true
  path: "reports/experiments.sqlite"
experiment:
  name: "nhits_fast_tri"
  notes: "config rápida focada em 3 tickers"

